### ISSUE TITLE
Should we have API or connectivity with meetup site e.g. MeetUp ?

### ISSUE THREAD

**Issue by mahasak** [ThaiProgrammer/tech-events-calendar#26]
This is just a rough idea to asked you guys about integration with existing meetup sites that community around here already use e.g. Meetup.

Pros:
* more content available, feed me more tech event and chance to see ppl.
* easier to draw contributor

Cons:
* too many content might be considered bad to users
* too complex ?
* idk

**Comment by dtinth** [comment]
Nice idea! I have thought about this. I think there are some fundamental differences between events system and this project.

| Events system (e.g meetup) | Calendar system (this project) |
| --- | --- |
| Event list is largely unorganized and unstructured | **Events categorized by type and topics**<br />Can drill down by interested topic |
| Provides each event information in detail | **Provides condensed event summary**<br />(280 chars intro, 3 paragraph description) |
| Event organizers can add events at will<br />(can lead to too much information) | **Content is curated by the community** |

These reasons are why I think automated importing of data from these systems can be very hard. Therefore, that’s why I intend for the data to be community-curated in the early stage.

For automatically curating data from e.g. Meetup, Event Pop, Devcamp, etc. let’s discuss on how we can map the data onto this system in a clean way. 😄

**Comment by dtinth** [comment]
For references, here are links to find meetups:

**Meetup\.com**
https://www.meetup.com/find/events/tech/?allMeetups=false&radius=50&userFreeform=Bangkok%2C+Thailand&mcName=Bangkok%2C+TH&lat=13.753998&lon=100.5014

**Event Pop**
https://www.eventpop.me/g/science-tech#events

**Facebook**
https://www.facebook.com/events/discovery/ (events from your network)
https://www.facebook.com/events/calendar/

**Event Brite**
https://www.eventbrite.com/d/thailand--bangkok/science-and-tech--events/?crt=regular&sort=date

**Devcamp**
https://dev.wi.th/events/calendar

**Comment by dtinth** [comment]
@parnurzeal [recommended](https://www.facebook.com/groups/ThaiPGAssociateSociety/permalink/823209907890280/?comment_id=823650997846171&notif_id=1519446570603686&notif_t=group_comment&ref=notif) Singapore’s https://webuild.sg/ for us to look as [a model for automatically syndicating meetup events](https://webuild.sg/faq). Looks really interesting!

However, some questions we need to tackle.

- How do we filter for only community events? (I don’t want to add commercial workshop/training courses to this calendar.)

- How do we make sure that all events (incl. those automatically syndicated) have proper summaries and descriptions?

- How do we make sure that our event information are kept up-to-date.

This is why I do it the other way at first: Instead of us automatically curating events, we manually curate some events, and have event organizers submit their events to the calendar, so that it’s in their mind to update our calendar. This helps set up a quality bar, and we can scale later. :)

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
