### ISSUE TITLE
Event detail inside Github Page?

### ISSUE THREAD

**Issue by MicroBenz** [ThaiProgrammer/tech-events-calendar#31]
Currently. The link in Github page now links to README to this project.I think it could be better if it display on the website directly.

**Comment by dtinth** [comment]
I plan to only display event title so that people can jump to full event details in GitHub.

There exists a project, [tech-events-browser](https://github.com/noobdevth/tech-events-browser), that displays the events in a beautiful webpage. It is developed by @phoomparin.

Maybe we can make that the official event viewer. Then the project page can have an official link “view events” that takes the user to tech events browser.

**Comment by mahasak** [comment]
[tech-events-browser](https://thai-tech-events.firebaseapp.com/) is looks cool, i will asked @phoomparin for his idea. If it's okay i will take that issue :D

**Comment by dtinth** [comment]
The project direction changed (#47) and now I decided to create an [official website](https://calendar.thaiprogrammer.org/) (#50). Now event summary is shown in the event list page. 😄
