### ISSUE TITLE
`yarn dev` doesn't load calendar data from public/calendar.json

### ISSUE THREAD

**Issue by suksit** [ThaiProgrammer/tech-events-calendar#74]
I tried to create an event, run `yarn build-json` and preview it using `yarn dev`, but the newly created event didn't show up.

So I looked at the code in `website/src/store.js` and it seems the site will always load calendar data from `https://thaiprogrammer-tech-events-calendar.spacet.me` but I think it should load the local calendar data when in development mode.

Or is this the intended behavior?

**Comment by dtinth** [comment]
It is that way for legacy reasons (the index.html file used to be a single HTML file with no build tool, and I test it without a web server. Since making requests to `file:///` URLs are not allowed in Chrome, I made it request the file from the main server always)...

Now that we have proper build tooling, I think it is fine to change it to always load from the current server (e.g. load from `/calendar.json`).

**Comment by dtinth** [comment]
Thanks for submitting many issues, by the way, I appreciate it a lot 😄

**Comment by unnawut** [comment]
Had the same problem as well. Would be great if someone could fix this :p

**Comment by dtinth** [comment]
I will put this issue as “helped wanted” and “good first issue” to encourage new contributors to make contributions to this project.

## How to fix

In `website/src/store.js`

https://github.com/ThaiProgrammer/tech-events-calendar/blob/227349dc3e3466a07426eba6f3ecaac1fc0e8566/website/src/store.js#L25-L29

These 5 lines can be changed into:

```js
        const events = await window.fetch('/calendar.json')
          .then((response) => response.json())
```

**Comment by suksit** [comment]
## Additional fix

I found that you also have to edit `website/build/webpack.dev.conf.js` and tell Webpack to copy files from `public` to the correct path when running dev server. First, find these lines of code:

https://github.com/ThaiProgrammer/tech-events-calendar/blob/43fc2ba7f0ac2be21535469a4c3a4af4e035a5c7/website/build/webpack.dev.conf.js#L60-L67

Then add another entry to the array:

```javascript
    // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.dev.assetsSubDirectory,
        ignore: ['.*']
      },
      {
        from: path.resolve(__dirname, '../../public'),
        to: '.',
        ignore: ['go', '_*']
      }
    ])
```
@dtinth could you please confirm this is the right way to do it?

**Comment by dtinth** [comment]
@suksit Yes, we can do it this way for development. 👍 

However, now the ways to bundle assets in development and productions are different:

- Dev: `public` &rarr; `website/dist` (due to CopyPlugin)
- Prod: `public` &larr; `website/dist` ([build script](https://github.com/ThaiProgrammer/tech-events-calendar/blob/43fc2ba7f0ac2be21535469a4c3a4af4e035a5c7/package.json#L22))

Ideally, the direction of files should be the same in both environments. But this can be fixed later. 😄

**Comment by suksit** [comment]
I believe I've found an elegant way to do this 😆
