### ISSUE TITLE
Documentation for developers

### ISSUE THREAD

**Issue by wiput1999** [ThaiProgrammer/tech-events-calendar#88]
I suggest that we should have documentation for developers. Like how you can use our JSON what each key mean? something else~~~ 😃

**Comment by dtinth** [comment]
I added the `good first issue` label to encourage more people to contribute to this project.

- If you are new to open source or this project, this issue is for you!
- If you are already a contributor, you can help by encouraging and helping your friend make their first contribution here.

---

Our public JSON dataset is in this URL:

https://thaiprogrammer-tech-events-calendar.spacet.me/calendar.json

But right now there's no documentation in the README file.

**Task:** Update the README file to document the structure of JSON file (in Thai language).

**Please comment on this issue if you want to work on it.** After commenting, please start working on it within one day (otherwise the task may be given to another person after inactivity). Feel free to ask any question here.

**Comment by wiput1999** [comment]
@dtinth Where should I put API documentation in markdown form?

**Comment by dtinth** [comment]
I can suggest 2 options:

Way 1: You can create a new file, docs/API.md, and update the README file
to add a link to it.

Way 2: You can put the documentation directly in README. Maybe at the
bottom.

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
