### ISSUE TITLE
Past events sorting order

### ISSUE THREAD

**Issue by kindraywind** [ThaiProgrammer/tech-events-calendar#99]
Should the `Past events` show in descending order?
IMO, It'd be more useful than seeing the first event in the db ever.
![screen shot 2018-03-08 at 10 19 33](https://user-images.githubusercontent.com/500289/37127681-395dd2ca-22ba-11e8-9286-052eac252caa.png)

**Comment by dtinth** [comment]
Thanks for reporting! The past event list is sorted the same way as upcoming events simply because it takes less code. 😜

But your suggestion makes sense, and I agree with it. I think it is more useful to see the recent events than always the first event in the DB.

**Comment by dtinth** [comment]
I added the `good first issue` label to encourage more people to contribute to this project.

- If you are new to open source or this project, this issue is for you!
- If you are already a contributor, you can help by encouraging and helping your friend make their first contribution here.

---

Please see the discussion above.

**Task:** Modify the web application to sort the past events in descending order (most recent events come first). The upcoming events page should not be affected.

Please check out the [README](https://github.com/ThaiProgrammer/tech-events-calendar#readme) file for instructions on setting up this project on your machine.

**Please comment on this issue if you want to work on it.** After commenting, please start working on it within one day (otherwise the task may be given to another person after inactivity). Feel free to ask any question here.
